// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRpJdMG_P-piHPR0arIPRNKB7BW2a6bhc',
    appId: '1:570175770407:web:228d8a20ba5fbefa24a302',
    messagingSenderId: '570175770407',
    projectId: 'finwiz-78e94',
    authDomain: 'finwiz-78e94.firebaseapp.com',
    storageBucket: 'finwiz-78e94.firebasestorage.app',
    measurementId: 'G-GYCGH2BYCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpSnA2w8Ptm0f1k7fzTdQ9BLyf0GLuhOQ',
    appId: '1:570175770407:android:d7446162185a0a6f24a302',
    messagingSenderId: '570175770407',
    projectId: 'finwiz-78e94',
    storageBucket: 'finwiz-78e94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKDgMFzuJzaoOOII6__nA_tClGiX76Tzs',
    appId: '1:570175770407:ios:123625065f4773a824a302',
    messagingSenderId: '570175770407',
    projectId: 'finwiz-78e94',
    storageBucket: 'finwiz-78e94.firebasestorage.app',
    iosBundleId: 'com.techpulse.finwiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKDgMFzuJzaoOOII6__nA_tClGiX76Tzs',
    appId: '1:570175770407:ios:123625065f4773a824a302',
    messagingSenderId: '570175770407',
    projectId: 'finwiz-78e94',
    storageBucket: 'finwiz-78e94.firebasestorage.app',
    iosBundleId: 'com.techpulse.finwiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRpJdMG_P-piHPR0arIPRNKB7BW2a6bhc',
    appId: '1:570175770407:web:620f6a382ac7025424a302',
    messagingSenderId: '570175770407',
    projectId: 'finwiz-78e94',
    authDomain: 'finwiz-78e94.firebaseapp.com',
    storageBucket: 'finwiz-78e94.firebasestorage.app',
    measurementId: 'G-MSN1EGSS97',
  );
}
